from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from enum import Enum


class PlatformEnum(str, Enum):
    android = "Android"
    ios = "iOS"


class DeviceStatusEnum(str, Enum):
    active = "Active"
    blocked = "Blocked"
    pending = "Pending"


class SessionStatusEnum(str, Enum):
    active = "Active"
    revoked = "Revoked"
    expired = "Expired"


# ── Auth ──────────────────────────────────────────────────────────────────────

class LoginRequest(BaseModel):
    username: str
    password: str
    device_id: str = Field(..., description="UUID generated by the mobile app")
    device_name: str
    platform: PlatformEnum
    app_version: str
    ip_address: Optional[str] = None


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    expires_in: int
    user: "UserInfo"
    device_status: DeviceStatusEnum


class RefreshRequest(BaseModel):
    refresh_token: str
    device_id: str


class UserInfo(BaseModel):
    user_id: str
    email: str
    full_name: str
    tenant_id: str
    roles: List[str] = []
    avatar: Optional[str] = None


# ── Device ────────────────────────────────────────────────────────────────────

class DeviceRegisterRequest(BaseModel):
    device_id: str
    device_name: str
    platform: PlatformEnum
    app_version: str
    ip_address: Optional[str] = None


class DeviceResponse(BaseModel):
    id: int
    device_id: str
    device_name: str
    platform: PlatformEnum
    app_version: str
    status: DeviceStatusEnum
    is_trusted: bool
    last_login: datetime
    ip_address: Optional[str] = None

    class Config:
        from_attributes = True


class DeviceValidateRequest(BaseModel):
    device_id: str
    user_id: str
    tenant_id: str


class ForceLogoutRequest(BaseModel):
    user_id: str
    tenant_id: str
    reason: Optional[str] = "Admin initiated force logout"


# ── AI ────────────────────────────────────────────────────────────────────────

class AIProvider(str, Enum):
    anthropic = "anthropic"
    openai = "openai"


class ChatMessage(BaseModel):
    role: str = Field(..., pattern="^(user|assistant|system)$")
    content: str


class ChatRequest(BaseModel):
    messages: List[ChatMessage]
    provider: AIProvider = AIProvider.anthropic
    model: Optional[str] = None
    temperature: float = Field(default=0.7, ge=0.0, le=2.0)
    max_tokens: int = Field(default=2048, ge=1, le=8192)
    erp_context: Optional[Dict[str, Any]] = None
    stream: bool = False


class ChatResponse(BaseModel):
    message: ChatMessage
    provider: str
    model: str
    usage: Dict[str, int]
    erp_actions: List[Dict[str, Any]] = []


class FileAnalysisRequest(BaseModel):
    file_type: str
    context: Optional[str] = None


class InsightRequest(BaseModel):
    doctype: str
    filters: Optional[Dict[str, Any]] = None
    period: Optional[str] = "last_30_days"


# ── ERP ───────────────────────────────────────────────────────────────────────

class ERPDocRequest(BaseModel):
    doctype: str
    name: Optional[str] = None
    filters: Optional[Dict[str, Any]] = None
    fields: Optional[List[str]] = None
    limit: int = Field(default=20, ge=1, le=500)
    order_by: Optional[str] = None


class ERPActionRequest(BaseModel):
    doctype: str
    name: str
    action: str
    data: Optional[Dict[str, Any]] = None


# ── WebSocket ─────────────────────────────────────────────────────────────────

class WSMessageType(str, Enum):
    force_logout = "force_logout"
    device_approved = "device_approved"
    device_blocked = "device_blocked"
    notification = "notification"
    ping = "ping"
    pong = "pong"


class WSMessage(BaseModel):
    type: WSMessageType
    payload: Optional[Dict[str, Any]] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


TokenResponse.model_rebuild()
